# Generated by Django 5.2.12 on 2026-03-21 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_category_alter_booking_status_booking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified_photographer_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='current_ping_radius',
            field=models.PositiveIntegerField(default=5, help_text='Current expanding ripple radius in kilometers.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
