# Generated by Django 5.2.12 on 2026-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_amount_paid_booking_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='10% Non-refundable', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.IntegerField(choices=[(4, '4 Hours'), (6, '6 Hours'), (8, '8 Hours')], default=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_payout_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_saved_by_photographer',
            field=models.BooleanField(default=False, help_text='Expands expiry if saved'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_ready_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled payout date (7 days after work)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
