# Generated by Django 5.2.12 on 2026-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_amount_paid_booking_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='placeholder_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
