# Generated by Django 5.2.12 on 2026-03-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_category_is_corporate_category_placeholder_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_qr_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gallery_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gallery_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gallery_link3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='overtime_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_qr_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='upload_penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
