# Generated by Django 5.2.12 on 2026-03-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_arrival_penalty_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code e.g. +919876543210', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_location',
            field=models.CharField(blank=True, help_text='Full venue / address of the event', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_purpose',
            field=models.CharField(blank=True, help_text='Purpose / description of the event', max_length=255),
        ),
    ]
