# Generated by Django 5.2.12 on 2026-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_booking_event_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration discount amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_order_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='First order 5% discount', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_drone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_shorts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total before discounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price after all discounts but before GST', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_hours',
            field=models.IntegerField(default=4),
        ),
    ]
