# Generated by Django 6.0.3 on 2026-03-21 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('base_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_travel_radius', models.PositiveIntegerField(help_text='Maximum travel distance in kilometers from photographer home base.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
