# Generated by Django 5.2.12 on 2026-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
