# Generated by Django 5.2.12 on 2026-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_photographerprofile_is_available'),
        ('bookings', '0004_booking_amount_paid_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='photographers', to='bookings.category'),
        ),
    ]
