# Generated by Django 5.2.12 on 2026-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_photographerprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='is_premium_partner',
            field=models.BooleanField(default=False, help_text='Entitles photographer to early notifications (5 min priority)'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
