# Generated by Django 5.2.12 on 2026-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell clients about yourself.'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photographer_profiles/'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='specialties',
            field=models.CharField(blank=True, help_text='Comma separated e.g. Panorama, Fish-eye, Low-light, Reels', max_length=500),
        ),
    ]
