# Generated by Django 5.2.12 on 2026-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_photographerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerprofile',
            name='specialties',
            field=models.CharField(blank=True, help_text='Comma-separated expertise (e.g. Panorama, Fish-eye)', max_length=500),
        ),
    ]
