# Generated by Django 5.2.12 on 2026-03-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_photographerprofile_specialties'),
        ('bookings', '0009_remove_booking_category_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_main_gallery', models.BooleanField(default=False, help_text='Show on the public homepage gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.category')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.photographerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
